### ISSUE TITLE
Responsiveness Issues

### ISSUE THREAD

**Issue by Jonak-Adipta-Kalita** [moiSentineL/moisentinel.github.io#10]
## Pic too big in Mobile Screen
![image](https://github.com/moiSentineL/moisentinel.github.io/assets/70377522/30f9d8e4-eb4c-4833-a18c-7603bedbdcb5)

## Title collapsing?
![image](https://github.com/moiSentineL/moisentinel.github.io/assets/70377522/8b1b2a09-da2e-4ab8-b0d1-c24bdd1dd9d5)

## Congested af
![image](https://github.com/moiSentineL/moisentinel.github.io/assets/70377522/7eecd2f4-e1cf-4196-a9aa-7fbf58c9aadb)

## Too big and unnecessary scrolling on smol screens
![image](https://github.com/moiSentineL/moisentinel.github.io/assets/70377522/2a75a852-0cc5-4993-801a-9801b79b1439)

**Comment by moiSentineL** [comment]
viewport problems, and I didn't add enough "points" in media queries: like tablets and stuff.

the pic size on mobile was deliberate tho. i want everyone to see my face lol.

**Comment by Jonak-Adipta-Kalita** [comment]
> viewport problems, and I didn't add enough "points" in media queries: like tablets and stuff.
> 
> the pic size on mobile was deliberate tho. i want everyone to see my face lol.

Understandable 😂
You can still move to Tailwind 🙃

**Comment by callmeVineeth** [comment]
Is this issue still open ? I you need any help regarding this issue , Feel free to connect. I am willing to help you.

**Comment by callmeVineeth** [comment]
Yeah sounds good.
 I will update you after proper analysis.

**Comment by moiSentineL** [comment]
i think it's fixed. there have been a couple of updates in improving UX
